"""Closed-loop demo: ``BangBangController`` drives ``base_link`` toward a CLI target.

Shape mirrors :mod:`dual_arm_satellite.teleop_live` (two live figures: pose-vs-time +
3D ``base_link``-frame view), but the input is a static world-frame target position
supplied on the command line, and each tick is generated by the controller rather
than by keyboard.

Per tick:

1. ``controller.calculate_control(engine, target_pose)`` -> :class:`ControlCommand`.
2. Joints are teleported to ``cmd.joint_positions_rad`` (simplifying assumption).
3. Any commanded thruster fires its impulse for ``dt``.
4. ``engine.step(dt)`` advances ``base_link`` pose under the resulting velocity.

The bang-bang policy has no velocity damping yet, so expect the bus to overshoot
and chatter around the target (classic limit cycle). The MVP is meant to show the
plumbing works end-to-end; smoother tracking comes with PID / Schmitt-trigger
hysteresis later.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d  # noqa: F401  # registers 3d projection
import numpy as np
from matplotlib.animation import FuncAnimation

from controller import BangBangController, ControlCommand
from physics_sim import BaseLinkPose, PhysicsSimEngine, Thruster
from physics_sim.plotting import plot_base_link_pose
from physics_sim.thrusters_3d import redraw_thrusters_in_base_frame

IDENTITY_QUAT_XYZW = np.array([0.0, 0.0, 0.0, 1.0])


def _apply_command(engine: PhysicsSimEngine, cmd: ControlCommand, dt_s: float) -> None:
    """Teleport joints, then fire any commanded thrusters with this tick's impulse window."""
    engine.set_joint_positions_rad(cmd.joint_positions_rad)
    if cmd.is_left_firing:
        engine.left_thruster.fire(engine, cmd.left_throttle, impulse_window_s=dt_s)
    if cmd.is_right_firing:
        engine.right_thruster.fire(engine, cmd.right_throttle, impulse_window_s=dt_s)


def _lock_3d_axes(ax_3d, half_extent_m: float) -> None:
    """Pin the base-frame 3D view to a fixed cube so per-frame arm motion doesn't rescale it.

    ``redraw_thrusters_in_base_frame`` calls ``ax.cla()`` and then auto-fits the
    limits to whatever it just drew. Calling this immediately after each redraw
    overrides that behaviour with a stable, isometric view.
    """
    r = float(half_extent_m)
    ax_3d.set_xlim3d(-r, r)
    ax_3d.set_ylim3d(-r, r)
    ax_3d.set_zlim3d(-r, r)
    try:
        ax_3d.set_box_aspect((1, 1, 1))
    except AttributeError:
        pass


def _build_engine_and_controller(
    *,
    max_thrust_n: float,
    dt_s: float,
    dist_err_threshold_m: float,
) -> Tuple[PhysicsSimEngine, BangBangController]:
    engine = PhysicsSimEngine.from_urdf(
        left_thruster=Thruster(
            side="left",
            max_thrust_n=max_thrust_n,
            impulse_window_s=dt_s,
        ),
        right_thruster=Thruster(
            side="right",
            max_thrust_n=max_thrust_n,
            impulse_window_s=dt_s,
        ),
    )
    controller = BangBangController(
        max_thrust_n=max_thrust_n,
        dist_err_threshold_m=dist_err_threshold_m,
    )
    return engine, controller


def run_headless(
    *,
    target_position_world_m: np.ndarray,
    duration_s: float,
    dt_s: float = 0.02,
    max_thrust_n: float = 20.0,
    dist_err_threshold_m: float = 0.01,
    save_plot_path: Optional[Path] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Run the controller loop without opening any matplotlib windows.

    Returns ``(times_s, positions_m, quaternions_xyzw)``.
    """
    engine, controller = _build_engine_and_controller(
        max_thrust_n=max_thrust_n,
        dt_s=dt_s,
        dist_err_threshold_m=dist_err_threshold_m,
    )
    target_pose = BaseLinkPose(
        position_m=np.asarray(target_position_world_m, dtype=float).reshape(3),
        quaternion_xyzw=IDENTITY_QUAT_XYZW.copy(),
    )

    times: List[float] = [0.0]
    positions: List[np.ndarray] = [engine.base_pose.position_m.copy()]
    quats: List[np.ndarray] = [engine.base_pose.quaternion_xyzw.copy()]

    n_steps = max(1, int(round(duration_s / dt_s)))
    sim_time_s = 0.0
    for _ in range(n_steps):
        cmd = controller.calculate_control(engine, target_pose)
        _apply_command(engine, cmd, dt_s)
        engine.step(dt_s)
        sim_time_s += dt_s
        times.append(sim_time_s)
        positions.append(engine.base_pose.position_m.copy())
        quats.append(engine.base_pose.quaternion_xyzw.copy())

    times_arr = np.asarray(times, dtype=float)
    positions_arr = np.stack(positions, axis=0)
    quats_arr = np.stack(quats, axis=0)

    if save_plot_path is not None:
        plot_base_link_pose(
            times_arr,
            positions_arr,
            quats_arr,
            title=f"Bang-bang control toward target = {tuple(target_pose.position_m)} (m)",
            save_path=save_plot_path,
            show=False,
        )
    return times_arr, positions_arr, quats_arr


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Closed-loop bang-bang position control demo. Live plots of base_link "
            "pose vs time and a 3D base-frame view of the arms and thrusters."
        )
    )
    p.add_argument(
        "--target",
        type=float,
        nargs=3,
        required=True,
        metavar=("X", "Y", "Z"),
        help="target world-frame position for base_link (m)",
    )
    p.add_argument("--dt", type=float, default=0.02, help="sim timestep (s)")
    p.add_argument(
        "--interval-ms",
        type=int,
        default=20,
        help="animation frame interval (ms)",
    )
    p.add_argument(
        "--max-thrust-n",
        type=float,
        default=5.0,
        help="per-thruster peak thrust force (N); applied to both arms",
    )
    p.add_argument(
        "--dist-err-threshold-m",
        type=float,
        default=0.01,
        help="position deadband (m): no fire when within this distance of target",
    )
    p.add_argument(
        "--duration",
        type=float,
        default=None,
        help="optional auto-stop time (s); omit to run until the window is closed",
    )
    p.add_argument(
        "--max-plot-points",
        type=int,
        default=6000,
        help="rolling history length for the live pose plot",
    )
    p.add_argument(
        "--thruster-arrow-m",
        type=float,
        default=0.22,
        help="thrust arrow length in the 3D base-frame view (m)",
    )
    p.add_argument(
        "--base-axes-m",
        type=float,
        default=0.12,
        help="base XYZ axis length in the 3D view (m)",
    )
    p.add_argument(
        "--view-half-m",
        type=float,
        default=1.2,
        help=(
            "half-extent (m) of the fixed 3D base-frame view cube; "
            "arms reach ~1.0 m from base origin, default leaves headroom"
        ),
    )
    p.add_argument(
        "--save",
        type=Path,
        default=None,
        metavar="PATH",
        help="after the run, save the pose-vs-time plot here",
    )
    p.add_argument(
        "--no-show",
        action="store_true",
        help="do not open interactive plot windows (requires --duration)",
    )
    return p.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> None:
    args = _parse_args(argv)

    if args.no_show and args.duration is None:
        raise SystemExit("--no-show requires --duration to bound the run")

    target_position = np.asarray(args.target, dtype=float)

    if args.no_show:
        times, positions, _ = run_headless(
            target_position_world_m=target_position,
            duration_s=args.duration,
            dt_s=args.dt,
            max_thrust_n=args.max_thrust_n,
            dist_err_threshold_m=args.dist_err_threshold_m,
            save_plot_path=args.save,
        )
        final_err = float(np.linalg.norm(positions[-1] - target_position))
        print(f"Done after {times[-1]:.3f} s. Final |position error| = {final_err:.4f} m")
        if args.save is not None:
            print(f"Saved pose-vs-time plot to {args.save.resolve()}")
        return

    engine, controller = _build_engine_and_controller(
        max_thrust_n=args.max_thrust_n,
        dt_s=args.dt,
        dist_err_threshold_m=args.dist_err_threshold_m,
    )
    target_pose = BaseLinkPose(
        position_m=target_position,
        quaternion_xyzw=IDENTITY_QUAT_XYZW.copy(),
    )

    sim_time_s = 0.0
    times: List[float] = [sim_time_s]
    positions: List[np.ndarray] = [engine.base_pose.position_m.copy()]
    quats: List[np.ndarray] = [engine.base_pose.quaternion_xyzw.copy()]

    fig, (ax_p, ax_q) = plt.subplots(
        2, 1, sharex=True, figsize=(10, 7), constrained_layout=True
    )
    try:
        fig.canvas.manager.set_window_title(
            f"Bang-bang control -> {tuple(target_position)}"
        )
    except Exception:
        pass
    fig.suptitle(
        f"Bang-bang position control toward target = {tuple(target_position)} (m)"
    )
    (lx,) = ax_p.plot([], [], label="x")
    (ly,) = ax_p.plot([], [], label="y")
    (lz,) = ax_p.plot([], [], label="z")
    ax_p.axhline(
        target_position[0], linestyle="--", linewidth=0.7, alpha=0.6, color=lx.get_color()
    )
    ax_p.axhline(
        target_position[1], linestyle="--", linewidth=0.7, alpha=0.6, color=ly.get_color()
    )
    ax_p.axhline(
        target_position[2], linestyle="--", linewidth=0.7, alpha=0.6, color=lz.get_color()
    )
    ax_p.set_ylabel("position (m); dashed = target")
    ax_p.legend(loc="upper right")
    ax_p.grid(True, alpha=0.3)

    (lqx,) = ax_q.plot([], [], label="qx")
    (lqy,) = ax_q.plot([], [], label="qy")
    (lqz,) = ax_q.plot([], [], label="qz")
    (lqw,) = ax_q.plot([], [], label="qw")
    ax_q.set_xlabel("time (s)")
    ax_q.set_ylabel("quaternion (xyzw)")
    ax_q.legend(loc="upper right")
    ax_q.grid(True, alpha=0.3)

    fig_3d = plt.figure(figsize=(7, 6))
    try:
        fig_3d.canvas.manager.set_window_title("Bang-bang - thrusters (base frame)")
    except Exception:
        pass
    ax_3d = fig_3d.add_subplot(111, projection="3d")
    redraw_thrusters_in_base_frame(
        ax_3d,
        engine,
        arrow_length_m=args.thruster_arrow_m,
        base_axes_length_m=args.base_axes_m,
    )
    _lock_3d_axes(ax_3d, args.view_half_m)

    stop_at_s = args.duration

    def _frame(_i: int):
        nonlocal sim_time_s
        if stop_at_s is not None and sim_time_s >= stop_at_s:
            anim.event_source.stop()
            return (lx, ly, lz, lqx, lqy, lqz, lqw)

        cmd = controller.calculate_control(engine, target_pose)
        _apply_command(engine, cmd, args.dt)
        engine.step(args.dt)
        sim_time_s += args.dt

        times.append(sim_time_s)
        positions.append(engine.base_pose.position_m.copy())
        quats.append(engine.base_pose.quaternion_xyzw.copy())
        if len(times) > args.max_plot_points:
            times.pop(0)
            positions.pop(0)
            quats.pop(0)

        t = np.asarray(times, dtype=float)
        P = np.stack(positions, axis=0)
        Q = np.stack(quats, axis=0)
        lx.set_data(t, P[:, 0])
        ly.set_data(t, P[:, 1])
        lz.set_data(t, P[:, 2])
        lqx.set_data(t, Q[:, 0])
        lqy.set_data(t, Q[:, 1])
        lqz.set_data(t, Q[:, 2])
        lqw.set_data(t, Q[:, 3])
        ax_p.relim()
        ax_p.autoscale_view()
        ax_q.relim()
        ax_q.autoscale_view()
        redraw_thrusters_in_base_frame(
            ax_3d,
            engine,
            arrow_length_m=args.thruster_arrow_m,
            base_axes_length_m=args.base_axes_m,
        )
        _lock_3d_axes(ax_3d, args.view_half_m)
        fig_3d.canvas.draw_idle()
        return (lx, ly, lz, lqx, lqy, lqz, lqw)

    anim = FuncAnimation(
        fig,
        _frame,
        interval=args.interval_ms,
        cache_frame_data=False,
    )
    try:
        plt.show()
    finally:
        if args.save is not None and times:
            plot_base_link_pose(
                np.asarray(times, dtype=float),
                np.stack(positions, axis=0),
                np.stack(quats, axis=0),
                title=f"Bang-bang control toward target = {tuple(target_position)} (m)",
                save_path=args.save,
                show=False,
            )
            print(f"Saved pose-vs-time plot to {args.save.resolve()}")


if __name__ == "__main__":
    main()
